// <auto-generated />
using System;
using K.Wms.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace K.Wms.Data.Migrations.App
{
    [DbContext(typeof(WmsAppContext))]
    partial class WmsAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("K.Wms.Data.Entity.Corporation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnName("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_corporations");

                    b.ToTable("corporations");
                });

            modelBuilder.Entity("K.Wms.Data.Entity.LegalForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("text");

                    b.Property<Guid>("CorporationId")
                        .HasColumnName("corporation_id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnName("country_code")
                        .HasColumnType("text");

                    b.Property<int>("LegalFormTypeId")
                        .HasColumnName("legal_form_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("VatId")
                        .HasColumnName("vat_id")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_legal_forms");

                    b.HasIndex("CorporationId")
                        .HasName("ix_legal_forms_corporation_id");

                    b.HasIndex("LegalFormTypeId")
                        .HasName("ix_legal_forms_legal_form_type_id");

                    b.ToTable("legal_forms");
                });

            modelBuilder.Entity("K.Wms.Data.Entity.LegalFormType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Country")
                        .HasColumnName("country")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_legal_form_types");

                    b.ToTable("legal_form_types");
                });

            modelBuilder.Entity("K.Wms.Data.Entity.LegalFormTypeName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<int>("LegalFormTypeId")
                        .HasColumnName("legal_form_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_legal_form_type_names");

                    b.HasIndex("LegalFormTypeId")
                        .HasName("ix_legal_form_type_names_legal_form_type_id");

                    b.ToTable("legal_form_type_names");
                });

            modelBuilder.Entity("K.Wms.Data.Entity.LegalForm", b =>
                {
                    b.HasOne("K.Wms.Data.Entity.Corporation", "Corporation")
                        .WithMany("LegalForms")
                        .HasForeignKey("CorporationId")
                        .HasConstraintName("fk_legal_forms_corporations_corporation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K.Wms.Data.Entity.LegalFormType", "LegalFormType")
                        .WithMany("LegalForms")
                        .HasForeignKey("LegalFormTypeId")
                        .HasConstraintName("fk_legal_forms_legal_form_types_legal_form_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("K.Wms.Data.Entity.LegalFormTypeName", b =>
                {
                    b.HasOne("K.Wms.Data.Entity.LegalFormType", "LegalFormType")
                        .WithMany("LegalFormTypeNames")
                        .HasForeignKey("LegalFormTypeId")
                        .HasConstraintName("fk_legal_form_type_names_legal_form_types_legal_form_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
